FORMAT: 1A
HOST: http://whatever.com/

# photoswhere

Photo where allows search of photos.  These photos contain information about where the
Photo was shot and any EXIF information

## Pictures Collection [/pictures]

### List All Pictures [GET]

+ Response 200 (application/json)

        [
            {
                "category": "Favorite pictures",
                "published_at": "2015-08-05T08:40:51.620Z",
                "pictures": [
                    {
                        "name": "Grand Canyon Secrets",
                        "lat": 00,
                        "lng": 00,
                        "stars": 3
                    },  {
                       "name": "Mystic Trails",
                       "lat": 00,
                       "lng": 00,
                       "stars": 5
                    },  {
                      "name": "No Long Stories",
                      "lat": 00,
                      "lng": 00,
                      "stars": 2
                    },  {
                      "name": "Dragons Layer",
                      "lat": 00,
                      "lng": 00,
                      "stars": 1
                    }
                ]
            }
        ]

### Create a New Photo [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "category": "Favorite pictures",
            "picture":
             {
                "name": "Jellystone Bears",
                "lat": 00,
                "lng": 00,
                "stars": 5
            }
        }

+ Response 201 (application/json)

    + Body

            {
                "added": "Jellystone Bears"
            }
        
            
+ Request (application/json)

            {
                "category": "Favorite pictures bad category",
                "picture":
                {
                    "name": "Jellystone Bears",
                    "lat": 00,
                    "lng": 00,
                    "stars": 5
                }
            }
        
+ Response 409 (application/problem+json)
             
            {
                "type": "some error",
                "title": "There is an update conflict",
                "detail": "The resource could not be updated, because it is based on an older version that was updated meanwhile. Get the new version, merge your data, and retry the update."
            }
            
        
### Update Photo Information [PUT]

+ Request

        { 
            "category": "Favorite picture",
             "picture":
            {
               "name": "Mystic Trails",
               "lat": 00, 
               "lng": 00,
                "stars": 5
            }
        }
        
+ Response 201

            {
                "updated": "Mystic Trails"Put 
            }
            
### Delete Photo Information [DELETE]

+ Response 204